### ISSUE TITLE
"RESOURCE_EXHAUSTED" and "Worker process with pid xxxx exited with code 1" issues with Java Azure Functions

### ISSUE THREAD

**Issue by SilicusShraddha** [Azure/azure-functions-java-worker#103]
Hi,

As per @JunyiYi suggestion [here](https://github.com/Azure/azure-functions-java-worker/issues/70#issuecomment-388515971) , I am opening a new ticket, though this seems to be an existing issue with java azure functions.
Even simplest Azure functions with java, replica of what shown [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven) are failing to respond. takes More than five minutes. I am using Maven Plugin version 0.2.1 for deployment.

Here are two scenarios, 

1. Using jar azure-functions-java-core 1.0.0-beta-2
     a. Java Functions successfully responds for first 6-7 requests.
     b. After 6-7 calls to azure function, getting -- **StatusRuntimeException-RESOURCE_EXAUSTED** exceptions
2. Using jar azure-functions-java-core 1.0.0-beta-3
     a. **No more facing** the StatusRuntimeException-RESOURCE_EXAUSTED.
     b. But this is leading to **"[Error] Microsoft.Azure.WebJobs.Host: Timeout value of 00:05:00"**, functions doesnt at all respond, and for some of the calls, the service even dont get interrupted.

As per @pragnagopa suggestions  [here](https://github.com/Azure/azure-functions-java-worker/issues/70#issuecomment-386358019) , tried everything, but no luck. The function just doesn't respond at all, and doesnt even kill the function call. It then gives

**"System.Private.CoreLib: One or more errors occurred. (Worker process with pid xxxx exited with code 1)"**

---Even I tried "stop" and "start" java functions, but the error **System.Private.CoreLib** still persists.
Please help.

**Comment by pragnagopa** [comment]
We have identified unresponsiveness of java functions to following to issues:
•	Loading functions with duplicate package names fails: https://github.com/Azure/azure-functions-java-worker/issues/68
•	Functions runtime was not handling invocations on functions that failed to load properly. This issue  https://github.com/Azure/azure-functions-host/pull/26 is fixed in the current release [v2.0.11737-alpha](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11737-alpha)03

@SilicusShraddha - Can you please verify if you have functions that have same package names? If you still facing same errors with latest runtime, can you please share your app name to help with further investigation?

**Comment by pragnagopa** [comment]
@JunyiYi - Do we have a sample that shows deploying multiple functions with in the same function app? If not, can you please share code here?

**Comment by JunyiYi** [comment]
@pragnagopa , you can put multiple functions in one package within one jar file. For example:
```
MyFunctionApp.jar
  --> com.sample.function.HttpFunction
  --> com.sample.function.TimerFunction
```

**Comment by pragnagopa** [comment]
Dup for #68
