### ISSUE TITLE
Investigate dependecy conflicts between worker and user code

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-java-worker#183]
An example of conflict #182 
Need to investigate how users can bring in their dependencies that conflict with Java worker

**Comment by asavaritayal** [comment]
At the moment, we have the following runtime dependencies for the language worker: 

- azure-functions-java-library
- protobuf-java
- grpc-protobuf
- grpc-stub
- grpc-netty
- guava
- commons-lang3
- commons-cli
- jackson-databind
- jackson-annotations
- javax.annotation-api
- junit

**Comment by asavaritayal** [comment]
From @brunoborges -

Only way I can think of is if you ensure user-defined dependencies are loaded first in the clasapath. But that may break the worker if user chooses an incompatible version of a dependency.

In other words: I don't think it is possible.

As I mentioned couple months ago, right now the architecture has worker and user code tightly coupled.

The ideal solution is to have user code running in one Java process, and the worker in another one.

This is how OpenFaaS and FN Project are designed.

**Comment by brunoborges** [comment]
Just to provide more details: the other option is to isolate user code with a different ClassLoader. But that imposes several other challenges.

**Comment by pragnagopa** [comment]
This issue becomes more important when we start supporting rich types as that would require worker to take dependency on azure libraries for each component

**Comment by pragnagopa** [comment]
Related issue #117 
Reducing worker dependencies on third party libraries and allowing the users to configure classpath might help

**Comment by Fabiest** [comment]
Hello,

Sorry for "re-opening" this.
I'm having a weird error with the jackson lib. I'm trying to use lib A that depends on jackson annotations 2.9.6. When i run my stuff under azure functions, the code fails because it cannot find property USER_DEFAULT from jackson code. Such property only exists after jackson 2.6.0.
Now, i've tried to force 2.9.6 from my pom and reading this thread, it makes no sense that i have this issue (first, it seems func worker was using 2.9.6 and it seems you have removed jsckson dependency to use gson).

What can i do? What is that alternative around the classpath? I'm not really  ajava developer so i'm not sure what i can do.

**Comment by Fabiest** [comment]
Hello,

I'm suffering from similar problem where I want to use lib A which depends on Jackson 2.9.6 (annotations, binding, core) and lib 8 which depends on Jackson 2.4.0 (annotations).

If i force version 2.9.6 in the pom and use my code in a "console" app, it works fine, but in a function it always complains with error "NoSuchFieldError: USE_DEFAULTS" which only exists after 2.6.0 in jackson annotations.

My work around, so far, was to force jackson annotations to 2.5.5 (the lowest maximum version i managed to make it work with) which was fine to work with lib A, but now this causes issues with lib azure-identity which needs 2.7.0 of jackson otherwise I get other errors...

Am I supposed to set something on the host.json file for the function?
