### ISSUE TITLE
Is it possible to inject third party logger in Java?

### ISSUE THREAD

**Issue by darewreck54** [Azure/azure-functions-java-worker#208]
Hi,

I was wondering if there is support to inject your own logger or to extend the existing logger.   I currently use logback/slfj and want to integrate that and not have to make two calls.  

Right now the function returns a final ExecutionContext which  you get grab the logger (getLogger()).  However, I want the getLogger() to return a custom version that extends the existing logger.

I was wondering is this currenlty supported or plans to support this?  

Thanks,
Derek

**Comment by pragnagopa** [comment]
We do not have support for this yet.

**Comment by Trosky** [comment]
Oh yes that would be awesome! It is really uncommon to use java.util.logging in the java community.

**Comment by stepio** [comment]
But extra dependencies make the resulting function heavier. So using native approach is a good idea as the only real difference is a little bit novel API.

**Comment by nzthiago** [comment]
Similarly to this feedback, we have worked recently with large enterprise customers who ask for support for JUL, Log4J (especially), and SFL4J as context loggers in Java Azure Functions. 
They use these loggers in their application and would not like to migrate to the Context Logger due to different API and impossibility of logging in static initializers.  (@asavaritayal FYI)

**Comment by asavaritayal** [comment]
+ @kulkarnisonia16 @jeffhollan FYI

**Comment by amamounelsayed** [comment]
This is now supported as a preview, https://github.com/Azure/azure-functions-java-worker/wiki/Distributed-Tracing-for-Java-Azure-Functions
