### ISSUE TITLE
JAVA_OPTS not working

### ISSUE THREAD

**Issue by Waxolunist** [Azure/azure-functions-java-worker#474]
Setting JAVA_OPTS does not have any effect.

I saw this PR, but it is not merged:

https://github.com/Azure/azure-functions-java-worker/pull/405

I also saw the discussions. But many libraries in the java world are assuming to get their settings via System.getProperty and not via System.getenv. So it does matter, that java developers can read System.getProperty.

Please explain how to set a system property, e.g. file.encoding or any custom property in a azure function with java 11.

**Comment by mDeisen** [comment]
Experiencing the same issue.
Running Java 11 with both consumption or dedicated service plan using linux, setting JAVA_OPTS has no effect.

When switching to a windows host, JAVA_OPTS work as expected. I would prefer running on linux. Is there a workaround or fix for this?

**Comment by kaibocai** [comment]
> Experiencing the same issue. Running Java 11 with both consumption or dedicated service plan using linux, setting JAVA_OPTS has no effect.
> 
> When switching to a windows host, JAVA_OPTS work as expected. I would prefer running on linux. Is there a workaround or fix for this?

Hi @mDeisen, thank you for providing the info. Can you provide more detailed how you verify this is not working? Thanks.

**Comment by mDeisen** [comment]
@kaibocai
I have a Java application that uses JVM parameters for configuration.
When deploying it using a Linux Consumption environment and setting JAVA_OPTS  as well as WEBSITE_USE_PLACEHOLDER set to 0 as described in: [Functions reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#customize-jvm) and reading/logging the value of the jvm parameters during runtime they are not set. The same happens when switching to the premium plan linux hosts.

Switching the application to a premium windows host, setting the same JAVA_OPTS (no need for the WEBSITE_USE_PLACEHOLDER), the values are set and can be read and used as expected during runtime.
No other changes were made to the code or deployment.

**Comment by kaibocai** [comment]
> @kaibocai I have a Java application that uses JVM parameters for configuration. When deploying it using a Linux Consumption environment and setting JAVA_OPTS as well as WEBSITE_USE_PLACEHOLDER set to 0 as described in: [Functions reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#customize-jvm) and reading/logging the value of the jvm parameters during runtime they are not set. The same happens when switching to the premium plan linux hosts.
> 
> Switching the application to a premium windows host, setting the same JAVA_OPTS (no need for the WEBSITE_USE_PLACEHOLDER), the values are set and can be read and used as expected during runtime. No other changes were made to the code or deployment.

Hi @mDeisen @Waxolunist, thanks very much for the providing the info. I did some validation on my side. For linux dedicated and premium, I saw JAVA_OPTS works as expected. 
Dedicated app setting: 
![image](https://user-images.githubusercontent.com/89094811/145851653-1708b1c9-6030-42cd-8d21-e2776e127075.png)Dedicated app printing info: 
![image](https://user-images.githubusercontent.com/89094811/145851723-937cbfdf-87c2-42aa-bf8b-b78ab0be8c37.png)

For consumption, please use languageWorkers__java__arguments instead of JAVA_OPTS in the app settings, sorry for the incorrect documents. We will update the documents soon. 
Consumption app setting: 
![image](https://user-images.githubusercontent.com/89094811/145851802-32656f4b-6597-42b1-949c-0bf95afe557c.png)Consumption app printing info: 
![image](https://user-images.githubusercontent.com/89094811/145851847-389865b7-d5a7-43ca-8c6b-594426ef5a99.png)
Thanks again for your info and help.

**Comment by kaibocai** [comment]
> Setting JAVA_OPTS does not have any effect.
> 
> I saw this PR, but it is not merged:
> 
> #405
> 
> I also saw the discussions. But many libraries in the java world are assuming to get their settings via System.getProperty and not via System.getenv. So it does matter, that java developers can read System.getProperty.
> 
> Please explain how to set a system property, e.g. file.encoding or any custom property in a azure function with java 11.

Hi @Waxolunist, thank you for the info. For the issue about System.getProperty, can you create a separate issue for it and provide more details how that affect you in your project. Thank you.

**Comment by amamounelsayed** [comment]
> @kaibocai I have a Java application that uses JVM parameters for configuration. When deploying it using a Linux Consumption environment and setting JAVA_OPTS as well as WEBSITE_USE_PLACEHOLDER set to 0 as described in: [Functions reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption#customize-jvm) and reading/logging the value of the jvm parameters during runtime they are not set. The same happens when switching to the premium plan linux hosts.
> 
> Switching the application to a premium windows host, setting the same JAVA_OPTS (no need for the WEBSITE_USE_PLACEHOLDER), the values are set and can be read and used as expected during runtime. No other changes were made to the code or deployment.

Thank you so much for your message, can you please share which config you are using and how did you validate it?

**Comment by Waxolunist** [comment]
@amamounelsayed @kaibocai JAVA_OPTS does not work on my linux function app, but languageWorkers__java__arguments does. To read the variable you actually have to read a set property with System.getProperty. If this is the solution (though not pretty), the ticket can be closed.

**Comment by kaibocai** [comment]
> languageWorkers__java__arguments

Hi @Waxolunist Thanks for your reply. Please see below code snippet for using System.getProperty to retrieve a property you set using languageWorkers__java__arguments. 
![image](https://user-images.githubusercontent.com/89094811/147491161-cd29da93-774b-4f2d-a227-194768f3d586.png)
in your azure function add configuration as 
![image](https://user-images.githubusercontent.com/89094811/147491214-f21ce1d1-a75b-45ad-8408-c80fd1b49f01.png)
On the webpage I can see the property after I trigger the function as
![image](https://user-images.githubusercontent.com/89094811/147491294-9e77925f-4a13-4ae8-a2da-41f2362decf0.png)
Please let me know if this answer your question on using System.getProperty to retrieve a property value. Thank you.
