### ISSUE TITLE
Swagger UI Not working with Azure function

### ISSUE THREAD

**Issue by mayurgupta** [Azure/azure-functions-java-worker#540]
I have tried running **spring-cloud-function-webmvc** app. and hit the /swagger-ui URL. I can see swagger UI comming up, 
But when i put Azure function plugin in pom. The swagger UI stops comming you.
I have attached modified version of this working project with Azure function here.

[spring-cloud-function-webmvc.zip](https://github.com/springdoc/springdoc-openapi-demos/files/8097480/spring-cloud-function-webmvc.zip)

now when i start this project, it scans the end point correctly. Below is the startup logs:
![image](https://user-images.githubusercontent.com/4255397/154690995-c1dd3939-fd45-40c7-88f7-f404170348dd.png)

But hitting the Swagger url gives the following error :
URL: http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html

![image](https://user-images.githubusercontent.com/4255397/154691166-161064bd-ccf9-4dd6-a4dd-52518c9ff901.png)

Is swagger UI not yet supported with Azure function?

Let me know if further info is required.

**Comment by kaibocai** [comment]
Hi @mayurgupta thanks for reaching out, if you see in your screen shot the url for http trigger function app is http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/uppercase instead of http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html, that's why you got 404 when you try to access http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html, cause the url is not the function app url. In other words, this url is not served by the function app you created. 

Also the function app defined in your code is not correct, here is a repo for [sample functions for java](https://github.com/Azure-Samples/azure-functions-samples-java), and [here is sample function for httptrigger](https://github.com/Azure-Samples/azure-functions-samples-java/blob/4ac36796a10df077c9617414de02b7e115928492/src/main/java/com/functions/Function.java#L31), please take a look and update your function app accordingly. 

Another issue I observed is that your host.json is out of date, can you update it as below
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Information",
      "Host.Results": "Error",
      "Host.Aggregator": "Information"
    },
    "console": {
      "isEnabled": "false"
    }
  }
}
```
Please let me know if this helps with your questions. Thanks.

**Comment by DineshSolanki** [comment]
> Hi @mayurgupta thanks for reaching out, if you see in your screen shot the url for http trigger function app is http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/uppercase instead of http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html, that's why you got 404 when you try to access http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html, cause the url is not the function app url. In other words, this url is not served by the function app you created.
> 
> Also the function app defined in your code is not correct, here is a repo for [sample functions for java](https://github.com/Azure-Samples/azure-functions-samples-java), and [here is sample function for httptrigger](https://github.com/Azure-Samples/azure-functions-samples-java/blob/4ac36796a10df077c9617414de02b7e115928492/src/main/java/com/functions/Function.java#L31), please take a look and update your function app accordingly.
> 
> Another issue I observed is that your host.json is out of date, can you update it as below
> 
> ```
> {
>   "version": "2.0",
>   "extensionBundle": {
>     "id": "Microsoft.Azure.Functions.ExtensionBundle",
>     "version": "[2.*, 3.0.0)"
>   },
>   "logging": {
>     "fileLoggingMode": "always",
>     "logLevel": {
>       "default": "Information",
>       "Host.Results": "Error",
>       "Host.Aggregator": "Information"
>     },
>     "console": {
>       "isEnabled": "false"
>     }
>   }
> }
> ```
> 
> Please let me know if this helps with your questions. Thanks.

I think he meant, if the azure function supports swagger-ui out of the box or he needs additional configuration, as it works fine when running as normal spring boot application but not when deployed on azure functions.
